name: Lock Threads

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  lock-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: dessant/lock-threads@7266a7ce5c1df01b1c6db85bf8cd86c737dadbe7 # v6.0.0
        with:
          process-only: issues
          issue-inactive-days: 30
          issue-comment: >
            This issue has been automatically locked since there
            has not been any recent activity after it was closed.
            Please open a new issue for related bugs.

  lock-prs:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: dessant/lock-threads@7266a7ce5c1df01b1c6db85bf8cd86c737dadbe7 # v6.0.0
        with:
          process-only: prs
          pr-inactive-days: 30
          pr-comment: >
            This pull request has been automatically locked since there
            has not been any recent activity after it was closed.
            Please open a new issue for related bugs.
