# workaround for https://github.com/actions/virtual-environments/issues/1281
name: Skip All Jobs

on:
  push:
    paths-ignore:
      - '**'
      - '!docs/**'
      - '!.cirrus.yml'
      - '!.github/workflows/docs.yml'
    branches:
      - master
      - develop
  pull_request:
    paths-ignore:
      - '**'
      - '!docs/**'
      - '!.cirrus.yml'
      - '!.github/workflows/docs.yml'
    branches:
      - '**'

jobs:
  tests:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    # we do not need os specific runners here, using linux is quicker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [Ubuntu, macOS, Windows]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - run: exit 0
